# Generated by Django 3.2.9 on 2022-01-17 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('filename', models.CharField(max_length=200)),
                ('date_uploaded', models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 33, 55, 248586))),
            ],
        ),
    ]
