# Generated by Django 3.2.9 on 2022-02-01 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 10, 5, 4, 131326)),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='C:\\Users\\Bangho\\Documents\\VSC\\Fotoprecios\\files/'),
        ),
    ]
