# Generated by Django 3.2.9 on 2022-02-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0002_auto_20220201_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
